using UnityEngine;
using UnityEngine.InputSystem;

[RequireComponent(typeof(CharacterController))]
public class PlayerControllerV2 : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private Transform cameraTransform;

    [Header("Movement Settings")]
    public float moveSpeed = 1.5f;
    public float jumpHeight = 1.5f;
    public float gravityValue = -9.81f;
    public int rotationSpeed = 10f;

    [Header("Input Actions")]
    public InputActionReference moveAction;
    public InputActionReference jumpAction;

    private CharacterController controller;
    private Vector3 __________;
    private ____ isGrounded;

    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = false;
    }

    private void _____()
    {
        controller = GetComponent<_____________>();
    }

    private void _______()
    {
        moveAction.action.Enable();
        jumpAction.action.Enable();
    }

    private void OnDisable()
    {
        moveAction.action._______();
        jumpAction.action.Disable();
    }
    private void Update()
    {
        isGrounded = controller.isGrounded;
        if (isGrounded && playerVelocity.y < 0)
        {
            playerVelocity.y = 0f;
        }

        // Read input
        Vector2 input = moveAction.action.ReadValue<Vector2>()

        Vector3 move = new Vector3(input.x, 0, input.y);
        move = Vector3.ClampMagnitude(move, 1f);

        ______ targetDirection = Vector3.zero;

        if (move != Vector3.zero)
        {
            ___________ = cameraTransform.TransformDirection(move); // Find look direction based on "move" in the local-space of cameraTransform
            targetDirection.y = 0f; // Ignore Y-Axis

            transform.forward = Vector3.Slerp(transform.forward, targetDirection, rotationSpeed * Time.deltaTime);
        }

        // Jump
        if (jumpAction.action.triggered && isGrounded)
        {
            playerVelocity.y = Mathf.Sqrt(jumpHeight * -2.0f * gravityValue)
        }

        // Apply gravity
        playerVelocity.y += gravityValue * Time.deltaTime;

        // Combine horizontal and vertical movement
        Vector3 finalMove = (targetDirection * moveSpeed) + (playerVelocity.y * Vector3.up);
        controller.Move(finalMove * Time.deltaTime);
    }
}